server:
  port: 9006
#注册到Eureka服务中⼼
eureka:
  client:
   service-url:
 # 注册到集群，就把多个Eurekaserver地址使⽤逗号连接起来即可；注册到单实例（⾮集群模式），那就写⼀个就ok
    defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true #服务实例中显示ip，⽽不是显示主机名（兼容⽼的eureka版本）
 # 实例名称： 192.168.1.103:lagou-service-resume:8080，我们可以⾃定义它
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
spring:
  application:
    name: lagou-config-server
  cloud:
    config:
      server:
        git:
         uri: https://github.com/springcloud2020/lagou-config-repo.git #配置git服务地址
         username: 1192816764@qq.com #配置git⽤户名
         password: wang010214 #配置git密码
         search-paths:
            - lagou-config-repo
      # 读取分⽀
      label: master
#针对的被调⽤⽅微服务名称,不加就是全局⽣效
#lagou-service-resume:
# ribbon:
# NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #负载策略调整
# springboot中暴露健康检查等断点接⼝
management:
 endpoints:
   web:
    exposure:
      include: "*"
 # 暴露健康接⼝的细节
 endpoint:
   health:
    show-details: always

